version: '3.7'


services:
    mongodb:
          image : mongo
          container_name: mongodb
          environment:
          - PUID=1000
          - PGID=1000
          volumes:
          - /home/barry/mongodb/database:/data/db
          ports:
                - 27017:27017
          restart: unless-stopped
    app:
        build: ./app
        container_name: app
        ports:
            - 8000:8000
        restart: unless-stopped
        depends_on:
            - mongodb